"""FastAPI application entry point for AI Patent Registration form.

Generated by Autonomous Product Studio (APS) - fill in the TODOs to ship.
"""
from fastapi import FastAPI

from app.api.routes import router

app = FastAPI(title="AI Patent Registration form", version="0.1.0")
app.include_router(router)


@app.get("/")
def root():
    return {"app": "AI Patent Registration form", "status": "scaffolded by APS"}
